# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "dh101"
tagline:          'Notes on preparing for work in digital humanities'
description:      ''
baseurl: '/dh101/'


author:
  name:           'Neel Smith'
 

paginate:         5

github:
  repo:           https://github.com/neelsmith/dh101

version:          0.12.0

links:
  - title: NS @ github
    url: http://neelsmith.github.io
    external: true
  - title: Github project
    url: https://github.com/cite-architecture/dh101
    external: true
   